/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'employer' : null } |
  { 'candidate' : null };
export interface Application {
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'createdAt' : Time,
  'jobId' : JobId,
  'portfolioUrl' : [] | [string],
  'message' : string,
  'candidate' : Principal,
}
export type ApplicationId = bigint;
export type ApplicationStatus = { 'hired' : null } |
  { 'submitted' : null } |
  { 'interview' : null } |
  { 'rejected' : null } |
  { 'reviewed' : null };
export interface Job {
  'id' : JobId,
  'title' : string,
  'published' : boolean,
  'description' : string,
  'employmentType' : string,
  'employer' : Principal,
  'skills' : Array<string>,
  'location' : string,
}
export type JobId = bigint;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'applicationId' : ApplicationId,
  'sender' : Principal,
  'timestamp' : Time,
}
export type MessageId = bigint;
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'description' : string,
  'accountType' : AccountType,
  'companyName' : string,
  'skills' : [] | [Array<string>],
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[JobId, string, [] | [string]], ApplicationId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<[AccountType, string], undefined>,
  'createJob' : ActorMethod<
    [string, string, string, string, Array<string>],
    JobId
  >,
  'deleteJob' : ActorMethod<[JobId], undefined>,
  'getApplicationsByCandidate' : ActorMethod<[Principal], Array<Application>>,
  'getApplicationsByJob' : ActorMethod<[JobId], Array<Application>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[JobId], [] | [Job]>,
  'getJobsByEmployer' : ActorMethod<[Principal], Array<Job>>,
  'getMessagesByApplication' : ActorMethod<[ApplicationId], Array<Message>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getPublishedJobs' : ActorMethod<[], Array<Job>>,
  'getTotalMembersCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchJobs' : ActorMethod<[string], Array<Job>>,
  'sendMessage' : ActorMethod<[ApplicationId, string], MessageId>,
  'toggleJobPublication' : ActorMethod<[JobId, boolean], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [ApplicationId, ApplicationStatus],
    undefined
  >,
  'updateJob' : ActorMethod<
    [JobId, string, string, string, string, Array<string>],
    undefined
  >,
  'updateProfile' : ActorMethod<
    [[] | [Array<string>], string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];