/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobId = IDL.Int;
export const ApplicationId = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountType = IDL.Variant({
  'employer' : IDL.Null,
  'candidate' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'hired' : IDL.Null,
  'submitted' : IDL.Null,
  'interview' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const Time = IDL.Int;
export const Application = IDL.Record({
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'createdAt' : Time,
  'jobId' : JobId,
  'portfolioUrl' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'candidate' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'accountType' : AccountType,
  'companyName' : IDL.Text,
  'skills' : IDL.Opt(IDL.Vec(IDL.Text)),
  'location' : IDL.Text,
});
export const Job = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'employmentType' : IDL.Text,
  'employer' : IDL.Principal,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const MessageId = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'applicationId' : ApplicationId,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func(
      [JobId, IDL.Text, IDL.Opt(IDL.Text)],
      [ApplicationId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccount' : IDL.Func([AccountType, IDL.Text], [], []),
  'createJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [JobId],
      [],
    ),
  'deleteJob' : IDL.Func([JobId], [], []),
  'getApplicationsByCandidate' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getApplicationsByJob' : IDL.Func([JobId], [IDL.Vec(Application)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getJobsByEmployer' : IDL.Func([IDL.Principal], [IDL.Vec(Job)], ['query']),
  'getMessagesByApplication' : IDL.Func(
      [ApplicationId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getPublishedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getTotalMembersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'sendMessage' : IDL.Func([ApplicationId, IDL.Text], [MessageId], []),
  'toggleJobPublication' : IDL.Func([JobId, IDL.Bool], [], []),
  'updateApplicationStatus' : IDL.Func(
      [ApplicationId, ApplicationStatus],
      [],
      [],
    ),
  'updateJob' : IDL.Func(
      [JobId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Opt(IDL.Vec(IDL.Text)), IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobId = IDL.Int;
  const ApplicationId = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountType = IDL.Variant({
    'employer' : IDL.Null,
    'candidate' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'hired' : IDL.Null,
    'submitted' : IDL.Null,
    'interview' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Application = IDL.Record({
    'id' : ApplicationId,
    'status' : ApplicationStatus,
    'createdAt' : Time,
    'jobId' : JobId,
    'portfolioUrl' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'candidate' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'accountType' : AccountType,
    'companyName' : IDL.Text,
    'skills' : IDL.Opt(IDL.Vec(IDL.Text)),
    'location' : IDL.Text,
  });
  const Job = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'employmentType' : IDL.Text,
    'employer' : IDL.Principal,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const MessageId = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'applicationId' : ApplicationId,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func(
        [JobId, IDL.Text, IDL.Opt(IDL.Text)],
        [ApplicationId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccount' : IDL.Func([AccountType, IDL.Text], [], []),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [JobId],
        [],
      ),
    'deleteJob' : IDL.Func([JobId], [], []),
    'getApplicationsByCandidate' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getApplicationsByJob' : IDL.Func(
        [JobId],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getJobsByEmployer' : IDL.Func([IDL.Principal], [IDL.Vec(Job)], ['query']),
    'getMessagesByApplication' : IDL.Func(
        [ApplicationId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getPublishedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getTotalMembersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'sendMessage' : IDL.Func([ApplicationId, IDL.Text], [MessageId], []),
    'toggleJobPublication' : IDL.Func([JobId, IDL.Bool], [], []),
    'updateApplicationStatus' : IDL.Func(
        [ApplicationId, ApplicationStatus],
        [],
        [],
      ),
    'updateJob' : IDL.Func(
        [JobId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Opt(IDL.Vec(IDL.Text)), IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };